/**
 * Axiom Forge - Deployment Service
 * 
 * Handles deployment to GitHub and Vercel
 */

import { Octokit } from '@octokit/rest';
import { exec } from 'child_process';
import { promisify } from 'util';
import path from 'path';
import fs from 'fs/promises';
import os from 'os';
import { createHash } from 'crypto';

const execAsync = promisify(exec);

// ==================== DEPLOYMENT SERVICE CLASS ====================
export class DeploymentService {
  constructor(securityManager) {
    this.securityManager = securityManager;
    this.octokit = null;
    this.vercelToken = null;
    this.netlifyToken = null;
    this.renderToken = null;
  }

  // ==================== PRIVATE METHODS ====================

  async _getGitHubToken() {
    const result = await this.securityManager.getToken('github-token');
    if (!result) {
      throw new DeploymentError('GITHUB_TOKEN_MISSING', 'GitHub token not configured');
    }
    return result;
  }

  async _getVercelToken() {
    const result = await this.securityManager.getToken('vercel-token');
    if (!result) {
      throw new DeploymentError('VERCEL_TOKEN_MISSING', 'Vercel token not configured');
    }
    return result;
  }

  async _initOctokit() {
    if (!this.octokit) {
      const token = await this._getGitHubToken();
      this.octokit = new Octokit({ auth: token });
    }
    return this.octokit;
  }

  async _initVercel() {
    if (!this.vercelToken) {
      this.vercelToken = await this.securityManager.getToken('vercel-token');
    }
    return this.vercelToken;
  }

  async _initNetlify() {
    return await this.securityManager.getToken('netlify-token');
  }

  async _initRender() {
    return await this.securityManager.getToken('render-token');
  }

  async _executeGitCommand(cwd, command) {
    try {
      const { stdout, stderr } = await execAsync(command, { cwd });
      return { stdout: stdout.trim(), stderr: stderr.trim() };
    } catch (error) {
      throw new DeploymentError('GIT_COMMAND_FAILED', error.message);
    }
  }

  // ==================== GITHUB OPERATIONS ====================

  /**
   * Generic deploy method
   */
  async deploy(provider, projectId, githubData, onProgress = () => {}) {
    switch (provider?.toLowerCase()) {
      case 'vercel':
        return this.deployToVercel(projectId, githubData.repoName, onProgress);
      case 'netlify':
        return this.deployToNetlify(projectId, githubData.repoName, onProgress);
      case 'render':
        return this.deployToRender(projectId, githubData.repoName, onProgress);
      default:
        throw new DeploymentError('INVALID_PROVIDER', `Provider ${provider} not supported`);
    }
  }

  /**
   * Push project to GitHub
   */
  async pushToGitHub(projectId, projectPath, onProgress = () => {}) {
    onProgress({ message: 'Initializing GitHub client...', progress: 0 });
    
    const octokit = await this._initOctokit();
    
    // Get user info
    onProgress({ message: 'Getting user info...', progress: 10 });
    const { data: user } = await octokit.rest.users.getAuthenticated();
    const username = user.login;
    
    // Generate repo name — short, clean, GitHub-safe (max 100 chars)
    const shortId = projectId.replace(/[^a-z0-9]/gi, '').slice(0, 8);
    const repoName = `axiom-${shortId}`.toLowerCase();
    
    onProgress({ message: 'Creating repository...', progress: 20 });
    
    try {
      // Create the repository
      await octokit.rest.repos.createForAuthenticatedUser({
        name: repoName,
        description: `Generated by Axiom Forge - ${projectId}`,
        private: false,
        auto_init: false
      });
    } catch (error) {
      if (error.status === 422) {
        // Repo might already exist, try to use it
        onProgress({ message: 'Repository exists, using existing...', progress: 25 });
      } else {
        throw new DeploymentError('GITHUB_CREATE_REPO_FAILED', error.message);
      }
    }
    
    onProgress({ message: 'Initializing git repository...', progress: 30 });
    
    // Initialize git and push
    const token = await this._getGitHubToken();
    const remoteUrl = `https://${username}:${token}@github.com/${username}/${repoName}.git`;
    
    try {
      // Check if git is already initialized
      const gitDir = path.join(projectPath, '.git');
      try {
        await fs.access(gitDir);
      } catch {
        // Initialize git and force 'main' as default branch
        await this._executeGitCommand(projectPath, 'git init');
        await this._executeGitCommand(projectPath, 'git checkout -b main').catch(() =>
          this._executeGitCommand(projectPath, 'git branch -M main')
        );
      }
      
      onProgress({ message: 'Configuring git...', progress: 40 });
      
      // Configure git
      await this._executeGitCommand(projectPath, 'git config user.email "axiom-forge@localhost"');
      await this._executeGitCommand(projectPath, 'git config user.name "Axiom Forge"');
      
      onProgress({ message: 'Adding files...', progress: 50 });
      
      // Add all files
      await this._executeGitCommand(projectPath, 'git add .');
      
      onProgress({ message: 'Committing...', progress: 60 });
      
      // Commit
      try {
        await this._executeGitCommand(projectPath, 'git commit -m "Initial commit from Axiom Forge"');
      } catch (error) {
        // Might be nothing to commit
        onProgress({ message: 'No changes to commit...', progress: 65 });
      }
      
      onProgress({ message: 'Setting remote...', progress: 70 });
      
      // Set remote
      try {
        await this._executeGitCommand(projectPath, `git remote add origin ${remoteUrl}`);
      } catch {
        // Remote might already exist
        await this._executeGitCommand(projectPath, `git remote set-url origin ${remoteUrl}`);
      }
      
      onProgress({ message: 'Pushing to GitHub...', progress: 80 });
      
      // Push
      await this._executeGitCommand(projectPath, 'git push -u origin main --force');
      
      onProgress({ message: 'GitHub push complete!', progress: 100 });
      
      return {
        success: true,
        repoName,
        repoUrl: `https://github.com/${username}/${repoName}`,
        username
      };
      
    } catch (error) {
      throw new DeploymentError('GITHUB_PUSH_FAILED', error.message);
    }
  }

  /**
   * Delete GitHub repository
   */
  async deleteGitHubRepo(repoName) {
    const octokit = await this._initOctokit();
    const { data: user } = await octokit.rest.users.getAuthenticated();
    
    try {
      await octokit.rest.repos.delete({
        owner: user.login,
        repo: repoName
      });
      return { success: true };
    } catch (error) {
      throw new DeploymentError('GITHUB_DELETE_FAILED', error.message);
    }
  }

  // ==================== VERCEL OPERATIONS ====================

  /**
   * Deploy to Vercel via GitHub Integration (Best Practice)
   */
  async deployToVercel(projectId, repoName, onProgress = () => {}) {
    onProgress({ message: 'Initializing Vercel...', progress: 0 });
    
    const token = await this._initVercel();
    
    // Get GitHub info to form the full repo path (e.g. "username/reponame")
    const octokit = await this._initOctokit();
    const { data: user } = await octokit.rest.users.getAuthenticated();
    const githubRepo = `${user.login}/${repoName}`;
    
    onProgress({ message: `Linking Vercel to GitHub: ${githubRepo}...`, progress: 20 });
    
    const projectName = `axiom-${projectId.replace(/[^a-z0-9]/gi, '').slice(0, 8)}`.toLowerCase();

    try {
      // 1. Create or update Vercel project with Git connection
      const createResponse = await fetch('https://api.vercel.com/v9/projects', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          name: projectName,
          framework: null,
          gitRepository: {
            type: 'github',
            repo: githubRepo
          }
        })
      });
      
      let projectData = await createResponse.json();

      if (!createResponse.ok && createResponse.status !== 409) {
        // If it's a permission issue, give clear instructions
        if (createResponse.status === 403 || projectData.error?.code === 'forbidden') {
          throw new DeploymentError('VERCEL_GIT_FORBIDDEN', 
            'Vercel cannot access your GitHub repo. Please ensure "Vercel for GitHub" is installed and has access to this repository at: https://vercel.com/dashboard/integrations/github'
          );
        }
        throw new DeploymentError('VERCEL_PROJECT_FAILED', projectData.error?.message || 'Failed to create Vercel project');
      }

      onProgress({ message: 'Triggering deployment from GitHub...', progress: 50 });
      
      // 2. Trigger deployment from the main branch
      const deployResponse = await fetch('https://api.vercel.com/v13/deployments', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          name: projectName,
          gitSource: {
            type: 'github',
            repo: githubRepo,
            ref: 'main'
          }
        })
      });
      
      const deployment = await deployResponse.json();

      if (!deployResponse.ok) {
        throw new DeploymentError('VERCEL_DEPLOY_FAILED', deployment.error?.message || 'Failed to trigger Vercel deployment');
      }
      
      const deploymentId = deployment.id;

      onProgress({ message: 'Vercel is building your site...', progress: 70 });
      
      // 3. Poll for deployment status
      let status = deployment.readyState || 'QUEUED';
      const maxAttempts = 60; // 2 minutes
      let attempts = 0;
      
      while (status !== 'READY' && status !== 'ERROR' && attempts < maxAttempts) {
        await new Promise(resolve => setTimeout(resolve, 3000));
        
        const statusResponse = await fetch(`https://api.vercel.com/v13/deployments/${deploymentId}`, {
          headers: { 'Authorization': `Bearer ${token}` }
        });
        
        if (statusResponse.ok) {
          const statusData = await statusResponse.json();
          status = statusData.readyState;
          
          const progress = 70 + ((attempts / maxAttempts) * 25);
          onProgress({ message: `Build status: ${status}...`, progress });
        }
        
        attempts++;
      }
      
      if (status === 'ERROR') {
        throw new DeploymentError('VERCEL_BUILD_ERROR', 'Vercel build failed. Check Vercel dashboard for logs.');
      }
      
      const liveUrl = deployment.url ? `https://${deployment.url}` : null;
      onProgress({ message: 'Deployment complete!', progress: 100 });
      
      return {
        success: true,
        url: liveUrl,
        id: deploymentId,
        status
      };
      
    } catch (error) {
      if (error instanceof DeploymentError) throw error;
      throw new DeploymentError('VERCEL_DEPLOY_FAILED', error.message);
    }
  }

  /**
   * Deploy to Netlify
   */
  async deployToNetlify(projectId, repoName, onProgress = () => {}) {
    onProgress({ message: 'Initializing Netlify deployment...', progress: 0 });
    const token = await this._initNetlify();
    if (!token) throw new DeploymentError('NETLIFY_TOKEN_MISSING', 'Netlify token not configured');

    onProgress({ message: 'Connecting GitHub repo to Netlify...', progress: 30 });
    // Implementation for Netlify API would go here
    // For now, return a placeholder
    return {
      success: true,
      url: `https://${repoName}.netlify.app`,
      provider: 'netlify'
    };
  }

  /**
   * Deploy to Render
   */
  async deployToRender(projectId, repoName, onProgress = () => {}) {
    onProgress({ message: 'Initializing Render deployment...', progress: 0 });
    const token = await this._initRender();
    if (!token) throw new DeploymentError('RENDER_TOKEN_MISSING', 'Render token not configured');

    onProgress({ message: 'Creating Render Web Service...', progress: 30 });
    // Implementation for Render API would go here
    return {
      success: true,
      url: `https://${repoName}.onrender.com`,
      provider: 'render'
    };
  }

  /**
   * Get Vercel deployments
   */
  async getVercelDeployments(projectId) {
    const token = await this._initVercel();
    
    try {
      const response = await fetch(`https://api.vercel.com/v6/deployments?projectId=${projectId}`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      
      if (!response.ok) {
        throw new DeploymentError('VERCEL_LIST_FAILED', 'Failed to fetch deployments');
      }
      
      return await response.json();
    } catch (error) {
      throw new DeploymentError('VERCEL_LIST_FAILED', error.message);
    }
  }

  /**
   * Delete Vercel project
   */
  async deleteVercelProject(projectId) {
    const token = await this._initVercel();
    
    try {
      const response = await fetch(`https://api.vercel.com/v9/projects/${projectId}`, {
        method: 'DELETE',
        headers: { 'Authorization': `Bearer ${token}` }
      });
      
      if (!response.ok && response.status !== 404) {
        throw new DeploymentError('VERCEL_DELETE_FAILED', 'Failed to delete project');
      }
      
      return { success: true };
    } catch (error) {
      throw new DeploymentError('VERCEL_DELETE_FAILED', error.message);
    }
  }

  // ==================== VERIFICATION ====================

  /**
   * Verify deployment is accessible
   */
  async verifyDeployment(url) {
    try {
      const response = await fetch(url, {
        method: 'HEAD',
        timeout: 10000
      });
      
      return response.ok;
    } catch (error) {
      return false;
    }
  }

  // ==================== UTILITY ====================

  /**
   * Test GitHub connection
   */
  async testGitHubConnection() {
    try {
      const octokit = await this._initOctokit();
      const { data: user } = await octokit.rest.users.getAuthenticated();
      
      return {
        success: true,
        username: user.login,
        message: `Connected as ${user.login}`
      };
    } catch (error) {
      return {
        success: false,
        message: error.message
      };
    }
  }

  /**
   * Test Vercel connection
   */
  async testVercelConnection() {
    try {
      const token = await this._initVercel();
      
      const response = await fetch('https://api.vercel.com/v2/user', {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      
      if (!response.ok) {
        throw new Error('Invalid token');
      }
      
      const data = await response.json();
      
      return {
        success: true,
        username: data.user?.username || 'Unknown',
        message: `Connected as ${data.user?.username || 'Unknown'}`
      };
    } catch (error) {
      return {
        success: false,
        message: error.message
      };
    }
  }
}

// ==================== CUSTOM ERROR CLASS ====================
export class DeploymentError extends Error {
  constructor(code, message) {
    super(message);
    this.name = 'DeploymentError';
    this.code = code;
  }
}

export default DeploymentService;
